/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 asian_female.gltf
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { scene, nodes, materials, animations } = useGLTF('/asian_female.gltf')

  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Blender" scale={1}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="Base_Eye">
            <skinnedMesh name="CC_Base_Eye" geometry={nodes.CC_Base_Eye.geometry} material={materials.Std_Eye_R} skeleton={nodes.CC_Base_Eye.skeleton} />
            <skinnedMesh name="CC_Base_Eye_1" geometry={nodes.CC_Base_Eye_1.geometry} material={materials.Std_Cornea_R} skeleton={nodes.CC_Base_Eye_1.skeleton} />
            <skinnedMesh name="CC_Base_Eye_2" geometry={nodes.CC_Base_Eye_2.geometry} material={materials.Std_Eye_L} skeleton={nodes.CC_Base_Eye_2.skeleton} />
            <skinnedMesh name="CC_Base_Eye_3" geometry={nodes.CC_Base_Eye_3.geometry} material={materials.Std_Cornea_L} skeleton={nodes.CC_Base_Eye_3.skeleton} />
          </group>
          <group name="Base_Teeth">
            <skinnedMesh name="CC_Base_Teeth" geometry={nodes.CC_Base_Teeth.geometry} material={materials.Std_Upper_Teeth} skeleton={nodes.CC_Base_Teeth.skeleton} />
            <skinnedMesh name="CC_Base_Teeth_1" geometry={nodes.CC_Base_Teeth_1.geometry} material={materials.Std_Lower_Teeth} skeleton={nodes.CC_Base_Teeth_1.skeleton} />
          </group>
          <skinnedMesh name="KG5_Top_862_Shape" geometry={nodes.KG5_Top_862_Shape.geometry} material={materials.Top_Fabric} skeleton={nodes.KG5_Top_862_Shape.skeleton} />
          <skinnedMesh name="Pants001" geometry={nodes.Pants001.geometry} material={materials.FABRIC_1_FRONT_5422} skeleton={nodes.Pants001.skeleton} />
          <group name="Sneakers__Shape">
            <skinnedMesh name="Sneakers_18172_Shape" geometry={nodes.Sneakers_18172_Shape.geometry} material={materials.Fabric} skeleton={nodes.Sneakers_18172_Shape.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_1" geometry={nodes.Sneakers_18172_Shape_1.geometry} material={materials.Inner} skeleton={nodes.Sneakers_18172_Shape_1.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_2" geometry={nodes.Sneakers_18172_Shape_2.geometry} material={materials.Plastic} skeleton={nodes.Sneakers_18172_Shape_2.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_3" geometry={nodes.Sneakers_18172_Shape_3.geometry} material={materials.Layer} skeleton={nodes.Sneakers_18172_Shape_3.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_4" geometry={nodes.Sneakers_18172_Shape_4.geometry} material={materials.Sole} skeleton={nodes.Sneakers_18172_Shape_4.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_5" geometry={nodes.Sneakers_18172_Shape_5.geometry} material={materials.Cord} skeleton={nodes.Sneakers_18172_Shape_5.skeleton} />
          </group>
          <group name="Base_Body">
            <skinnedMesh name="CC_Base_Body" geometry={nodes.CC_Base_Body.geometry} material={materials.Std_Skin_Head} skeleton={nodes.CC_Base_Body.skeleton} morphTargetDictionary={nodes.CC_Base_Body.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_1" geometry={nodes.CC_Base_Body_1.geometry} material={materials.Std_Skin_Body} skeleton={nodes.CC_Base_Body_1.skeleton} morphTargetDictionary={nodes.CC_Base_Body_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_1.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_2" geometry={nodes.CC_Base_Body_2.geometry} material={materials.Std_Skin_Arm} skeleton={nodes.CC_Base_Body_2.skeleton} morphTargetDictionary={nodes.CC_Base_Body_2.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_2.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_3" geometry={nodes.CC_Base_Body_3.geometry} material={materials.Std_Skin_Leg} skeleton={nodes.CC_Base_Body_3.skeleton} morphTargetDictionary={nodes.CC_Base_Body_3.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_3.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_4" geometry={nodes.CC_Base_Body_4.geometry} material={materials.Std_Nails} skeleton={nodes.CC_Base_Body_4.skeleton} morphTargetDictionary={nodes.CC_Base_Body_4.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_4.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_5" geometry={nodes.CC_Base_Body_5.geometry} material={materials.Std_Eyelash} skeleton={nodes.CC_Base_Body_5.skeleton} morphTargetDictionary={nodes.CC_Base_Body_5.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_5.morphTargetInfluences} />
          </group>
          <skinnedMesh name="Base_Tongue" geometry={nodes.Base_Tongue.geometry} material={materials.Std_Tongue} skeleton={nodes.Base_Tongue.skeleton} morphTargetDictionary={nodes.Base_Tongue.morphTargetDictionary} morphTargetInfluences={nodes.Base_Tongue.morphTargetInfluences} />
          <group name="Nini_Hair">
            <skinnedMesh name="Nini_Hair_1" geometry={nodes.Nini_Hair_1.geometry} material={materials.Hair_Transparency} skeleton={nodes.Nini_Hair_1.skeleton} morphTargetDictionary={nodes.Nini_Hair_1.morphTargetDictionary} morphTargetInfluences={nodes.Nini_Hair_1.morphTargetInfluences} />
            <skinnedMesh name="Nini_Hair_2" geometry={nodes.Nini_Hair_2.geometry} material={materials.Front_Hair_Transparency} skeleton={nodes.Nini_Hair_2.skeleton} morphTargetDictionary={nodes.Nini_Hair_2.morphTargetDictionary} morphTargetInfluences={nodes.Nini_Hair_2.morphTargetInfluences} />
            <skinnedMesh name="Nini_Hair_3" geometry={nodes.Nini_Hair_3.geometry} material={materials.Base_Transparency} skeleton={nodes.Nini_Hair_3.skeleton} morphTargetDictionary={nodes.Nini_Hair_3.morphTargetDictionary} morphTargetInfluences={nodes.Nini_Hair_3.morphTargetInfluences} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/asian_female.gltf')
