/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 try2.glb --output asian_model_2.jsx
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera, useAnimations, useTexture } from '@react-three/drei'

export function AsianModel2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/try2.glb');
  const topFabricDiffuse = useTexture('/Top_Fabric_Diffuse.jpg');
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Blender" scale={0.05}>
          <primitive object={nodes.CC_Base_BoneRoot} />
          <group name="Base_Body">
            <skinnedMesh name="CC_Base_Body" geometry={nodes.CC_Base_Body.geometry} material={materials.Std_Skin_Head} skeleton={nodes.CC_Base_Body.skeleton} morphTargetDictionary={nodes.CC_Base_Body.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_1" geometry={nodes.CC_Base_Body_1.geometry} material={materials.Std_Skin_Body} skeleton={nodes.CC_Base_Body_1.skeleton} morphTargetDictionary={nodes.CC_Base_Body_1.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_1.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_2" geometry={nodes.CC_Base_Body_2.geometry} material={materials.Std_Skin_Arm} skeleton={nodes.CC_Base_Body_2.skeleton} morphTargetDictionary={nodes.CC_Base_Body_2.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_2.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_3" geometry={nodes.CC_Base_Body_3.geometry} material={materials.Std_Skin_Leg} skeleton={nodes.CC_Base_Body_3.skeleton} morphTargetDictionary={nodes.CC_Base_Body_3.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_3.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_4" geometry={nodes.CC_Base_Body_4.geometry} material={materials.Std_Nails} skeleton={nodes.CC_Base_Body_4.skeleton} morphTargetDictionary={nodes.CC_Base_Body_4.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_4.morphTargetInfluences} />
            <skinnedMesh name="CC_Base_Body_5" geometry={nodes.CC_Base_Body_5.geometry} material={materials.Std_Eyelash} skeleton={nodes.CC_Base_Body_5.skeleton} morphTargetDictionary={nodes.CC_Base_Body_5.morphTargetDictionary} morphTargetInfluences={nodes.CC_Base_Body_5.morphTargetInfluences} />
          </group>
          <group name="Base_Eye">
            {/* <skinnedMesh name="CC_Base_Eye" geometry={nodes.CC_Base_Eye_1.geometry} material={materials.Std_Cornea_R} skeleton={nodes.CC_Base_Eye_1.skeleton} /> */}
            <skinnedMesh name="CC_Base_Eye_1" geometry={nodes.CC_Base_Eye.geometry} material={materials.Std_Eye_R} skeleton={nodes.CC_Base_Eye.skeleton} />
            <skinnedMesh name="CC_Base_Eye_2" geometry={nodes.CC_Base_Eye_2.geometry} material={materials.Std_Eye_L} skeleton={nodes.CC_Base_Eye_2.skeleton} />
            {/* <skinnedMesh name="CC_Base_Eye_3" geometry={nodes.CC_Base_Eye_3.geometry} material={materials.Std_Cornea_L} skeleton={nodes.CC_Base_Eye_3.skeleton} /> */}
          </group>
          <group name="Base_Teeth">
            <skinnedMesh name="CC_Base_Teeth" geometry={nodes.CC_Base_Teeth.geometry} material={materials.Std_Upper_Teeth} skeleton={nodes.CC_Base_Teeth.skeleton} />
            <skinnedMesh name="CC_Base_Teeth_1" geometry={nodes.CC_Base_Teeth_1.geometry} material={materials.Std_Lower_Teeth} skeleton={nodes.CC_Base_Teeth_1.skeleton} />
          </group>
          <skinnedMesh name="Base_Tongue" geometry={nodes.Base_Tongue.geometry} material={materials.Std_Tongue} skeleton={nodes.Base_Tongue.skeleton} morphTargetDictionary={nodes.Base_Tongue.morphTargetDictionary} morphTargetInfluences={nodes.Base_Tongue.morphTargetInfluences} />
          <skinnedMesh name="KG5_Top_862_Shape" geometry={nodes.KG5_Top_862_Shape.geometry} material={materials.Top_Fabric} skeleton={nodes.KG5_Top_862_Shape.skeleton} />
          <group name="Nini_Hair">
            <skinnedMesh name="Nini_Hair_1" geometry={nodes.Nini_Hair_1.geometry} material={materials.Hair_Transparency} skeleton={nodes.Nini_Hair_1.skeleton} morphTargetDictionary={nodes.Nini_Hair_1.morphTargetDictionary} morphTargetInfluences={nodes.Nini_Hair_1.morphTargetInfluences} />
            <skinnedMesh name="Nini_Hair_2" geometry={nodes.Nini_Hair_2.geometry} material={materials.Front_Hair_Transparency} skeleton={nodes.Nini_Hair_2.skeleton} morphTargetDictionary={nodes.Nini_Hair_2.morphTargetDictionary} morphTargetInfluences={nodes.Nini_Hair_2.morphTargetInfluences} />
            {/* <skinnedMesh name="Nini_Hair_3" geometry={nodes.Nini_Hair_3.geometry} material={materials.Base_Transparency} skeleton={nodes.Nini_Hair_3.skeleton} morphTargetDictionary={nodes.Nini_Hair_3.morphTargetDictionary} morphTargetInfluences={nodes.Nini_Hair_3.morphTargetInfluences} /> */}
          </group>
          <skinnedMesh name="Pants001" geometry={nodes.Pants001.geometry} material={materials.FABRIC_1_FRONT_5422} skeleton={nodes.Pants001.skeleton}/>
          <group name="Sneakers__Shape">
            <skinnedMesh name="Sneakers_18172_Shape" geometry={nodes.Sneakers_18172_Shape.geometry} material={materials.Fabric} skeleton={nodes.Sneakers_18172_Shape.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_1" geometry={nodes.Sneakers_18172_Shape_1.geometry} material={materials.Inner} skeleton={nodes.Sneakers_18172_Shape_1.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_2" geometry={nodes.Sneakers_18172_Shape_2.geometry} material={materials.Plastic} skeleton={nodes.Sneakers_18172_Shape_2.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_3" geometry={nodes.Sneakers_18172_Shape_3.geometry} material={materials.Layer} skeleton={nodes.Sneakers_18172_Shape_3.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_4" geometry={nodes.Sneakers_18172_Shape_4.geometry} material={materials.Sole} skeleton={nodes.Sneakers_18172_Shape_4.skeleton} />
            <skinnedMesh name="Sneakers_18172_Shape_5" geometry={nodes.Sneakers_18172_Shape_5.geometry} material={materials.Cord} skeleton={nodes.Sneakers_18172_Shape_5.skeleton} />
          </group>
        </group>
        <group name="Right_3iid_1245" position={[2.07, 0.88, 1.15]} rotation={[-1.2, 1.14, 1.22]} />
        <pointLight name="Light" intensity={0} decay={2} position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} />
        <OrthographicCamera name="Camera" makeDefault={false} far={100} near={100} position={[0.01, -1.66, 1.6]} rotation={[1.5, 0.02, 0]} />
        <spotLight name="Key_3iid_1244" intensity={0} angle={0.38} penumbra={0.75} decay={2} distance={7.5} position={[0.31, -4.57, 2.57]} rotation={[1.4, 0.06, -1.49]}>
          <group position={[0, 0, -1]} />
        </spotLight>
        <spotLight name="Ear_3iid_1246" intensity={0} angle={0.55} penumbra={1} decay={2} distance={9.1} position={[0.67, 1.91, 1.7]} rotation={[-1.34, 0.35, 1.49]}>
          <group position={[0, 0, -1]} />
        </spotLight>
      </group>
    </group>
  )
}

useGLTF.preload('/try2.glb')
